version: '3.7'

networks:
  discord-monit-db:

services:
  aws:
    image: ghcr.io/mndrke/discord-monit-db:latest
    container_name: discord_monit_db_container
    networks:
      - discord-monit-db
    env_file:
      - .env
